<?php 
$listeactions = array("Collecting food",
"Crying themselves to sleep",
"Failed to make spears",
"Talked to their spirit about winning",
"Talked to their spirit about losing",
"Reminisced on the past",
"Thought about betraying their spirit",
"Cleaned their toenails",
"Took a bath",
"Ate soap",
"Lost sight of their goals",
"Ate some cookies they baked",
"Threw up",
"Killed themselves, but was okay",
"Failed to kill themselves",
"Looked up at the sky",
"Prayed",
"Chopped down some trees with the bare knuckles",
"Fought with their spirit",
"Licked some plants",
"Tore their clothes",
"Discovered the beauty of nudism",
"Shaved their beard with a rock",
"Made a fire",
"Slept through the day ",
"Rented a hotel",
"Watched a beetle eat a rabbit",
"Watched (participant 2) sleep",
"Ate (participant 2)’s shoes",
"Stole (participant 2)’s supplies",
"Failed to tie a noose",
"Cursed at the moon for the things happening to them",
"Wished they weren’t part of this killing game",
"Got aroused by an oddly shaped tree",
"Cooked meatloaf then dropped it",
"Found cooked meatloaf on the ground and ate it",
"Digested poison, but was completely fine",
"Tried to build a wall but forgot what a wall looked like",
"Attempted to change their eye color with a flower",
"Forgot their name",
"Cut their hair",
"Found a coconut with no trees in sight",
"Saw a monkey eating a banana",
"Pondered how to win the game",
"Worried about their homework assignments",
"Feared that he wouldn’t be able kill anyone before the game ended",
"Cleaned (participant 2)’s fingernails",
"Dreamed about stuffing their mouth",
"Saw an egg-shaped storm cloud",
"Stole then lost a car",
"Thought about getting vengeance on their ex",
"Stared at the sun til it hurt",
"Forgor",
"Tested their typing speed, got 32wpm",
"Found and kept some cocaine",
"Snorted (participant 2’s) beef jerky",
"Stabbed a squirrel",
"Ran from a squid",
"Was perplexed by the notion of someone not knowing what onomatopoeia means",
"Found out they were British",
"Worked on their woodworking skills",
"Bewitched a witch, then got dumped",
"Snuggled up in their snuggie and fell asleep",
"Watched (participant 2) fail to tie a noose",
"Had someone carve them a spear at gunpoint",
"Packed their bags and got ready to fight",
"Earned $20 dollars, one or the other",
"Tamed Cthulu, then let him go",
"Snored",
"Introduced (participant 2) to their girlfriend",
"Boiled some meat",
"Filmed 2 koalas fighting",
"Yelled for help",
"Snatched up and ate a gecko",
"Requested that (participant 2) help them out in their next fight",
"Weighed themselves on a weight before climbing a mountain",
"Tested (participant 2) for rabies after they had been bitten",
"Trained their muscles",
"Wailed in pain after tripping",
"Dreaded what was to come","Coiled in his own mortal tomb",
"Complained about his teammate, (person 2)",
"Decided they were going to live on, for the future",
"Became the hero of humanity",
"flew sky high after discovering some plants",
"Pricked their feet on some rose bushes",
"Groaned about their situation",
"Talked to themselves",
"Try to mine for iron",
"Carried some rocks to make a bed",
"Drowned some flowers symbolically",
"Travelled to the countryside",
"Hunted people in the country",
"Missed sleeping in a bed",
"Listened to another participant fight",
"Scratched an itch",
"Harassed some women",
"Carved a spear, then lost it",
"Robbed a nearby individual for their pepper spray",
"Kissed their own reflection in a mirror",
"Measured their growth since the beginning of the game",
"Learned that not every animal is nice",
"Attended a lecture unknowingly",
"Trapped someone in a school",
"is alive",
"Jogged to stretch",
"Strengthened their resolve",
"Tipped off their parent about their imminent demise",
"Permitted a 9-year-old to cross the street",
"Imitated the buzzing sound that a bee makes",
"Spoke straight fax about minorities",
"Choked out a 2-year-old for calling them stinky",
"Found out they lost 200 pounds since the beginning of the game",
"Found out they were stinky",
"Teased someone about something",
"Sneezed",
"Escaped a sticky situation",
"Called the cops to take them home",
"Haunted their dog to death",
"Regretted clicking yes on the terms and services without reading",
"Tumbled down a hill into a lake",
"Separate two twins at birth",
"Reunited two twins that had been separated",
"Got laid",
"Accomplished everything on their bucket list",
"Spoiled attack on titan for every person they could find",
"Scattered after the cops showed up at the party",
"Attached their dog and cat together to recreate that one show",
"Scraped their knee",
"Healed their scraped hand",
"Pretended everything was okay to their parents",
"Flamed their spirit",
"Squashed a bug",
"Found out more about the origin of the game from their spirit",
"Forced themselves to continue the game",
"Licked their wounds clean",
"Squashed an ant",
"Compared their life from before the game to now",
"Wrapped up a weapon and hid it in their sleeve",
"Disarmed a venus fly trap",
"Figure out what the point of them continuing was",
"Wondered how long spirits have been around, helping people win",
"Thought about the existence of things similar to spirits",
"Hummed a song they hard many a year ago",
"Applauded someone after they had won a fight",
"Dried their clothes off after they fell in a puddle",
"Visited their grandparents, one final time",
"Longed to be the winner of the game",
"Obtained something no one else had",
"Grabbed food out of a window",
"Delighted at the idea they got to kill (Person 2)",
"Questioned the existence of both the game and their spirit",
"Wondered if the other players also got their own spirits",
"Attracted many mosquitos",
"Flashed (participant 2)",
"Mended their broken arm",
"Amused their liege, in hopes to not be executed",
"Invented interdimensional travel, then got mugged and lost it",
"Reported a crime after they saw someone get mugged",
"Numbered the amount of remining participants",
"Spilled their drink into their backpack",
"Tricked their spirit into believing they intended on winning",
"Started making their way towards the sounds of nearby fighting",
"Practiced their karate chops, which they saw in a movie",
"Watered their new garden, hoping something will continue their legacy",
"Waited for someone to find them",
"Got suspended from school",
"Knocked on the wrong person’s door",
"Worked to ensure their survival",
"Told their spirit off",
"Disagreed with their spirit and flamed them",
"Prepared to kill their best friend",
"Leveled out an area to sleep on",
"Greased up their phone, just in case",
"Rose up to the challenge",
"Attempted to steal a car, only to lose their right shoe",
"Broke a lightswitch in rage",
"Queued up in league",
"Trapped a fish in a desert",
"Dressed up their dog in armor",
"Supplied (participant 2) with food and supplies",
"Rolled a 1 on a d20 to see how the was going to go",
"Enjoyed their final moments",
"Realized their hate for (participant 2), and set out",
"Offered a store owner a sponsorship",
"Saw a black person and cried",
"Bounced on out of there",
"Realized the folly of their actions",
);
?>